In [1]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("selected.csv", index_col = 0)

In [4]:
df

219340_s_at  217771_at  202418_at  206295_at  201091_s_at  204015_s_at  \
0       7.014110   9.938705  11.053083   5.326001    10.964107     6.244280   
1       7.326724   6.374728  10.596457   8.290123    11.594716     6.542130   
2       6.974651   9.226757  10.834848   5.731169     9.166088     6.586000   
3       7.703683   8.169183  11.627066   8.538247     9.086937     8.477335   
4       6.581141   7.496745  11.500773   5.979282     8.887616     7.398170   
..           ...        ...        ...        ...          ...          ...   
193     6.954604  10.129438  10.888537   6.915913    10.740020     6.139044   
194     4.108023   8.701039  10.908745   6.655799    11.145993     7.044179   
195     5.667819  10.940586  10.464572   6.845962    10.463171     9.980030   
196     7.466355  10.032314  10.894581   7.338324     8.609631    10.528216   
197     6.429858  10.722343  11.692123   6.939691     9.011730     9.160088   

     200726_at  200965_s_at  210314_x_at  221882_s_at  ...  t.dmfs  e.dmfs  \
0    10.926361     8.962608    10.523859    10.926365  ...     723       1   
1    12.242090     9.531718    10.342614     9.555092  ...    6591       0   
2    11.661716    10.238680    10.144875     9.308048  ...     524       1   
3    12.174021     9.819279    10.888251    10.208241  ...    6255       1   
4    11.484011    11.489233     9.702690    10.931843  ...    3822       1   
..         ...          ...          ...          ...  ...     ...     ...   
193  12.018292     8.323876     8.839213     9.604668  ...    5673       0   
194  11.711415    10.428482     9.634663    11.067820  ...     404       1   
195  11.939616     9.615587     9.424510     7.743568  ...    2225       0   
196  11.848449    10.528911    10.517222     9.298178  ...    2722       0   
197  11.425778     9.901486     9.631856     8.958376  ...    1781       0   

     t.tdm  e.tdm  risksg    NPI  risknpi  AOL_os_10y  risk_AOL  veridex_risk  
0      723      1       2    4.6        2        62.7         1          Poor  
1     6591      0       2    4.6        2        69.0         1          Poor  
2      524      1       2    4.5        2        66.2         1          Poor  
3     6255      0       2   4.36        2        84.9         1          Poor  
4     3822      1       2    3.6        2        80.2         1          Poor  
..     ...    ...     ...    ...      ...         ...       ...           ...  
193   5673      0       2   4.44        2        67.7         1          Poor  
194    404      1       2   4.64        2        62.7         0          Poor  
195   2225      0       2    2.5        1        87.6         1          Poor  
196   2722      0       2   3.24        1        89.6         0          Good  
197   1781      0       2    4.5        2        67.7         1          Poor  

[198 rows x 103 columns]

In [98]:
df = df.replace("NA",np.nan)

In [99]:
df.dropna(inplace = True, axis = 0)

In [100]:
df.dtypes

219340_s_at     float64
217771_at       float64
202418_at       float64
206295_at       float64
201091_s_at     float64
                 ...   
NPI              object
risknpi          object
AOL_os_10y      float64
risk_AOL          int64
veridex_risk     object
Length: 103, dtype: object

In [101]:
removals = ['t.rfs',
 'e.rfs',
 't.os',
 'e.os',
 't.dmfs',
 'e.dmfs',
 't.tdm',
 'e.tdm', "samplename", "id","filename","hospital",'age', 'size', 'Surgery_type', 'Histtype', 'Angioinv',
       'Lymp_infil', 'node', 'grade', 'er', 'risksg', 'NPI', 'risknpi',
       'AOL_os_10y', 'risk_AOL', 'veridex_risk']
rest = [i for i in df.columns if i not in removals]

In [102]:
X = df[rest]

In [103]:
X.columns

Index(['219340_s_at', '217771_at', '202418_at', '206295_at', '201091_s_at',
       '204015_s_at', '200726_at', '200965_s_at', '210314_x_at', '221882_s_at',
       '217767_at', '219588_s_at', '204073_s_at', '212567_s_at', '211382_s_at',
       '201663_s_at', '221344_at', '210028_s_at', '218782_s_at', '201664_at',
       '219724_s_at', '204014_at', '212014_x_at', '202240_at', '204740_at',
       '208180_s_at', '204768_s_at', '203391_at', '211762_s_at', '218914_at',
       '221028_s_at', '211779_x_at', '218883_s_at', '204888_s_at', '217815_at',
       '201368_at', '201288_at', '201068_s_at', '218478_s_at', '214919_s_at',
       '209835_x_at', '217471_at', '203306_s_at', '205034_at', '221816_s_at',
       '219510_at', '217102_at', '208683_at', '215510_at', '218533_s_at',
       '215633_x_at', '221928_at', '214806_at', '204540_at', '221916_at',
       '216693_x_at', '209500_x_at', '209524_at', '207118_s_at', '211040_x_at',
       '218430_s_at', '217404_s_at', '205848_at', '214915_at', '2160

In [104]:
y = df["t.dmfs"]

In [105]:
from sklearn import linear_model
reg = linear_model.LassoLars(alpha=.1, normalize=False)
reg.fit(X,y)

LassoLars(alpha=0.1, normalize=False)

In [106]:
lr = linear_model.LinearRegression(normalize = True)
lr.fit(X,y)

LinearRegression(normalize=True)

In [107]:
lr.score(X,y)

0.4106224416975477

In [108]:
reg.score(X, y)

0.41062079934459184

In [109]:
lr.coef_

array([  83.17967455,  -49.97105625, -657.2513066 ,  271.16865752,
         73.38496032, -393.84361116,  -31.50871102, -237.29420443,
       -539.78701457,  421.99636549, -125.07134248,  565.30591631,
         95.0695251 ,  245.05723933,  529.16090387, -248.96157263,
         28.99856164,   50.31094638, -223.30088919, -217.24392009,
        158.73661457,  384.76700776, -299.16000782, -452.57998681,
         96.36795968, -123.40964721,    3.71342004,  150.68795923,
        150.56796416, -946.6424955 , -279.56583482, -116.9725961 ,
       -840.2024471 , -127.5945108 ,  115.58160035, -108.6938405 ,
       -127.7835623 , -145.56755028,  507.60340888, -113.68534705,
        436.49161809,   79.95819969,  355.05675079,  276.21504992,
       -124.20891218,   33.56026565,   51.91374392, -106.33537362,
        109.81181888, -127.82140011,  426.2400789 ,  -10.67736564,
       -383.51494287,   -8.28489621,  204.74832133,  621.55975078,
       -146.34055823, -443.70309389, -268.41705942,  545.24349

In [110]:
df

219340_s_at  217771_at  202418_at  206295_at  201091_s_at  204015_s_at  \
0       7.014110   9.938705  11.053083   5.326001    10.964107     6.244280   
1       7.326724   6.374728  10.596457   8.290123    11.594716     6.542130   
2       6.974651   9.226757  10.834848   5.731169     9.166088     6.586000   
3       7.703683   8.169183  11.627066   8.538247     9.086937     8.477335   
4       6.581141   7.496745  11.500773   5.979282     8.887616     7.398170   
..           ...        ...        ...        ...          ...          ...   
193     6.954604  10.129438  10.888537   6.915913    10.740020     6.139044   
194     4.108023   8.701039  10.908745   6.655799    11.145993     7.044179   
195     5.667819  10.940586  10.464572   6.845962    10.463171     9.980030   
196     7.466355  10.032314  10.894581   7.338324     8.609631    10.528216   
197     6.429858  10.722343  11.692123   6.939691     9.011730     9.160088   

     200726_at  200965_s_at  210314_x_at  221882_s_at  ...  t.dmfs  e.dmfs  \
0    10.926361     8.962608    10.523859    10.926365  ...     723       1   
1    12.242090     9.531718    10.342614     9.555092  ...    6591       0   
2    11.661716    10.238680    10.144875     9.308048  ...     524       1   
3    12.174021     9.819279    10.888251    10.208241  ...    6255       1   
4    11.484011    11.489233     9.702690    10.931843  ...    3822       1   
..         ...          ...          ...          ...  ...     ...     ...   
193  12.018292     8.323876     8.839213     9.604668  ...    5673       0   
194  11.711415    10.428482     9.634663    11.067820  ...     404       1   
195  11.939616     9.615587     9.424510     7.743568  ...    2225       0   
196  11.848449    10.528911    10.517222     9.298178  ...    2722       0   
197  11.425778     9.901486     9.631856     8.958376  ...    1781       0   

     t.tdm  e.tdm  risksg    NPI  risknpi  AOL_os_10y  risk_AOL  veridex_risk  
0      723      1       2    4.6        2        62.7         1          Poor  
1     6591      0       2    4.6        2        69.0         1          Poor  
2      524      1       2    4.5        2        66.2         1          Poor  
3     6255      0       2   4.36        2        84.9         1          Poor  
4     3822      1       2    3.6        2        80.2         1          Poor  
..     ...    ...     ...    ...      ...         ...       ...           ...  
193   5673      0       2   4.44        2        67.7         1          Poor  
194    404      1       2   4.64        2        62.7         0          Poor  
195   2225      0       2    2.5        1        87.6         1          Poor  
196   2722      0       2   3.24        1        89.6         0          Good  
197   1781      0       2    4.5        2        67.7         1          Poor  

[198 rows x 103 columns]

In [112]:
from sklearn.model_selection import train_test_split

In [113]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.10, random_state=42)

In [114]:
lr = linear_model.LinearRegression(normalize = True)
lr.fit(X_train,y_train)

LinearRegression(normalize=True)

In [115]:
lr.predict(X_test)

array([8943.11842671, 3054.94015383, 4185.4477327 , 2034.41933695,
       6520.89176675, 4353.74064953, 3745.38418267, 5914.42043674,
       4115.6782846 , 4947.95643317, 4546.2021478 , 3845.39377024,
       4531.79724348, 3406.33625956, 2440.5101833 , 2878.25001992,
       5466.46104483, 5207.60830373, 5358.79714827, 3860.94029464])

In [117]:
lr.score(X_test, y_test)

-0.4684198141093281

In [120]:
from sklearn import svm
regr = svm.SVR()

In [121]:
regr.fit(X_train, y_train)

SVR()

In [122]:
regr.score(X_test, y_test)

-0.04484144503104348

In [123]:
regr.predict(X_test)

array([4339.83727151, 4338.8581222 , 4338.29386474, 4337.45508407,
       4340.11711103, 4338.93055889, 4338.51932129, 4339.93919637,
       4338.45383034, 4338.22787215, 4339.80599259, 4337.30660757,
       4337.91959332, 4337.13945902, 4337.97982558, 4338.87031693,
       4338.29968847, 4338.63718906, 4340.00940186, 4337.83480726])

In [124]:
y_test

65     4642
114     394
16      434
141    5917
156    5768
126    6399
140     805
30     4675
18     2863
167    6232
158    5530
15      994
55     5238
56     5101
115    6777
45     4791
124     289
9      1233
147    5779
85     3293
Name: t.dmfs, dtype: int64